### ISSUE TITLE
empty fits

### ISSUE THREAD

**Issue by fmannucci** [thespacedoctor/panstamps#11]
Hi, I'm trying to get fits images with this command:
fitsPaths, jpegPaths, colorPath = panstamps.downloader(
    log=logger,
    ra=6.47225779439, dec=+7.84289619078,
    settings=False,
    fits=True,
    jpeg=True,
    arcsecSize=60,
    filterSet='r',
    color=False,
    singleFilters=True,
    imageType="stack",
    mjdStart=False,
    mjdEnd=False,
    window=False).get()
I get the both jpeg and fits files, but while the jpeg are fine, the fits files are empty (have 13kb of size). I had no problem a few weeks ago (but using another computer).
I use:
panstamps v0.6.4
Python 3.8.16
astroquery 0.4.6
Thanks

**Comment by thespacedoctor** [comment]
Hi @fmannucci - thanks for reporting. I can confirm I can reproduce this issue. Looking into it now.

**Comment by thespacedoctor** [comment]
The issue was in the encoding of the URLs on the new ps1images webserver. Decoding the URLs seems to have fixed the issues. v0.6.5 is now released and on pypi.

Want to try `pip install panstamps --upgrade` and test your code again?

**Comment by fmannucci** [comment]
Thanks for fixing the issue. I confirm that it is solved!
