### ISSUE TITLE
Command line issue: g-filter not properly converted to jpeg?

### ISSUE THREAD

**Issue by swiggumj** [thespacedoctor/panstamps#2]
I'm working through some of the command line examples after installing (e.g. `panstamps -Fjc stack [ra] [dec]`) and 5/1 stack/color jpeg files are downloaded respectively. I've tried running this command for various ra/dec, but always get the error:

`Traceback (most recent call last):
  File "/anaconda3/envs/py2/bin/panstamps", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/envs/py2/lib/python2.7/site-packages/panstamps/cl_utils.py", line 228, in main
    oneImage.get()
  File "/anaconda3/envs/py2/lib/python2.7/site-packages/panstamps/image/image.py", line 267, in get
    im.save(self.imagePath)
  File "/anaconda3/envs/py2/lib/python2.7/site-packages/PIL/Image.py", line 1930, in save
    save_handler(self, fp, filename)
  File "/anaconda3/envs/py2/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 607, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode RGBA as JPEG`

When I do an `ls -lh`, all the files are there, but the g-filter file is zero size. Finally, the annotation isn't showing up on any of the stack/color plots. Any thoughts?

Thanks in advance.

**Comment by thespacedoctor** [comment]
Can you send me an example coordinate set and I'll see if I can reproduce the issue?

**Comment by swiggumj** [comment]
Hi David,

I used “pip install panstamps” to install, then tried going through the command line tutorial. For example:

“panstamps -Fj --filters=gri --downloadFolder=[path] stack 09:55:52.2 +69:40:47”

The command throws an error (IOError: cannot write mode RGBA as JPEG), but JPEG files (grizy; I thought it should only be gri) are written to the chosen directory. The final file written (g-filter) is zero size. When downloading FITS files (no “-Fj”), there is no error and all files appear to be written properly. 

Any ideas? Let me know if you need a more detailed description. Thanks for looking into this!

Cheers,
Joe

**Comment by thespacedoctor** [comment]
I did a fresh install of panstamps and can reproduce this issue. It seems to be due to a change in the pillow package, because if I install a previous version the issue goes away:

```bash
> pip install pillow==3.4.2
> panstamps -Fj --filters=gri --downloadFolder=~/Desktop/test stack 09:55:52.2 +69:40:47
  5 / 5 (100.0%) URLs downloaded
```

Here's an example image:

![stack_g_ra148.967500_dec69.679722_arcsec60_skycell2552.048][stack_g_ra148.967500_dec69.679722_arcsec60_skycell2552.048 40223552501]

[stack_g_ra148.967500_dec69.679722_arcsec60_skycell2552.048 40223552501]: https://farm5.staticflickr.com/4669/40223552501_32ca70b5aa_o.jpg 

I'll continue investigating

**Comment by thespacedoctor** [comment]
pillow now issues an error if you try and save an alpha channel to a JPEG (not possible). See [here](https://github.com/python-pillow/Pillow/issues/2609) 

> JPEGs can't represent an alpha channel. It's been issuing a warning for a while, removed in this release.

So a very simple fix on my end. Try updating panstamps.

**Comment by swiggumj** [comment]
Thanks for looking into this — will try again!

Joe
