### ISSUE TITLE
no files found?

### ISSUE THREAD

**Issue by boada** [thespacedoctor/panstamps#3]
Giving it the following command... 

```
$ panstamps --width=4 stack 15:46:50.301 +69:56:38.82
```
Tells me there are no files to be found. However, if you look at the link that panstamps provides, there are images available.. 

```
http://plpsipp1v.stsci.edu/cgi-bin/ps1cutouts?filter=g&filter=r&filter=i&catlist=&autoscale=99.500000&verbose=0&output_size=1200&filetypes=stack&pos=15%3A46%3A50.301+%2B69%3A56%3A38.82&size=960
* 08:46:55 - WARNING: /home/boada/.local/lib/python2.7/site-packages/panstamps-0.5.2-py2.7.egg/panstamps/downloader.py:get:228 > No images found. Your options may not be set correctly. Here's the requested URL:
http://plpsipp1v.stsci.edu/cgi-bin/ps1cutouts?filter=g&filter=r&filter=i&catlist=&autoscale=99.500000&verbose=0&output_size=1200&filetypes=stack&pos=15%3A46%3A50.301+%2B69%3A56%3A38.82&size=960
```
Am I missing a specific option?

**Comment by thespacedoctor** [comment]
hi @boada thanks for reporting.

It seems that the web-interface has introduced helpful warnings when requesting images near the poles:

![](https://farm8.staticflickr.com/7857/46356585894_bb63c5a393_o.png)

<http://plpsipp1v.stsci.edu/cgi-bin/ps1cutouts?filter=g&filter=r&filter=i&catlist=&autoscale=99.500000&verbose=0&output_size=1200&filetypes=stack&pos=15%3A46%3A50.301+%2B69%3A56%3A38.82&size=960>

These warnings have broken my regex that looks for the image in the HTML - I'll push a quick fix through soon.

**Comment by thespacedoctor** [comment]
@boada can you try a `pip install panstamps --upgrade` and run your command again. Should work now.

**Comment by boada** [comment]
Thanks @thespacedoctor seems to work great.

Hopefully, we'll see some Python3 support next. =)
