### ISSUE TITLE
No images found

### ISSUE THREAD

**Issue by jermainegug** [thespacedoctor/panstamps#4]
Seems like I am getting something very similar to issue #3. 
 
Trying to get fits images as demonstrated in the documentation but when I run

```
panstamps stack 09:55:52.2 +69:40:47
```

I get this:

```
default settings have been added to '/home/username/.config/panstamps/panstamps.yaml'. Tailor these settings before proceeding to run panstamps
* 18:27:21 - WARNING: /home/username/.local/lib/python2.7/site-packages/panstamps/downloader.py:get:228 > No images found. Your options may not be set correctly. Here's the requested URL:
http://plpsipp1v.stsci.edu/cgi-bin/ps1cutouts?filter=g&filter=r&filter=i&catlist=&autoscale=99.500000&verbose=0&output_size=1200&filetypes=stack&pos=09%3A55%3A52.2+%2B69%3A40%3A47&size=240
```

Which is saying that no images are found but there are clearly images in the link. I have run this off a fresh install, so I have not changed anything in `panstamps.yaml`. Any ideas on what might be the problem here?

**Comment by thespacedoctor** [comment]
Hi jermainegug, can you try and do a 'pip install fundamentals --upgrade' then the command again? I think there may have been a bug in the underlying download code I use.

**Comment by jermainegug** [comment]
Yep. That has fixed it! :) 
Thanks heaps.
