### ISSUE TITLE
download large Panstars image

### ISSUE THREAD

**Issue by duyhoang-astro** [thespacedoctor/panstamps#6]
Hi. I would like to download Panstars images that have large field of view (e.g. 1 degree in size).  However, Panstars can only download images with max sizes of 6000x6000 pixels. The pixel size of the Panstars image is 0.25 arcsec (got from the fits header). This limits the max sizes of 0.4x0.4 degˆ2. Is there any options that increases the Panstars image? Thanks.

**Comment by thespacedoctor** [comment]
Hi @duyhoang2014 . Unfortunately this is a limit enforced by the PanSTARRS image server at MAST which I have no control over. It might be worth reaching out to them.
