### ISSUE TITLE
Problem with installation in Python 3 version

### ISSUE THREAD

**Issue by irhamta** [thespacedoctor/panstamps#7]
Hi, 

Recently, I installed the latest panstamps version (in Python 3), but it doesn't work correctly. The `panstamps init` command doesn't create `~/.config/panstamps/panstamps.yaml` file. Then, when I tried to download image by using `panstamps stack 09:55:52.2 +69:40:47`, I got this error:

```
Traceback (most recent call last):
  File "/home/irhamta/anaconda3/envs/panstamps3/bin/panstamps", line 8, in <module>
    sys.exit(main())
  File "/home/irhamta/anaconda3/envs/panstamps3/lib/python3.8/site-packages/panstamps/cl_utils.py", line 120, in main
    if a["init"]:
KeyError: 'init'
```

Do you know how to solve this? Thanks in advance!

**Comment by thespacedoctor** [comment]
Thanks @irhamta - a few teething issues from upgrading to python 3. Will fix very soon

**Comment by thespacedoctor** [comment]
Hi @irhamta can you try a `pip install panstamps --upgrade` and test again please? I think all is well now.

I'll close this issue, but feel free to re-open if the issue remains.
